<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Abstractions" Version="29.0.3" />
    <PackageReference Include="CK.Configuration" Version="0.11.3" />
    <PackageReference Include="CK.PerfectEvent" Version="27.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.14" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.DeviceModel\CK.IO.DeviceModel.csproj" />
  </ItemGroup>
</Project>